### ISSUE TITLE
failed to upload environment setting - FFI_Yajl::ParseError:

### ISSUE THREAD

**Issue by swade1987** [chef/chef-server#100]
Hi all,

I am trying to update a cookbook version on my Chef 12.0.3 environment file.

The source code for this is [here](http://hastebin.com/imabewafes.pl)

However, when it comes to uploading I obtain the following error

    ERROR: FFI_Yajl::ParseError: lexical error: invalid char in json text.
                                       ???{"name":"ci","description":"
                     (right here) ------^
failed to upload environment setting
At C:\Chef\chef_cookbooks\steven.ps1:32 char:5
+     throw "failed to upload environment setting"
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (failed to upload environment setting:String) [], RuntimeException
    + FullyQualifiedErrorId : failed to upload environment setting

Any anyone shed some light on how to resolve this please?

**Comment by stevendanna** [comment]
This is likely a chef-client(knife) issue related to encoding rather than a Chef Server bug.  One possibility is that the code you have to remove the byte-order marker isn't correct (although, I don't see any problem with it).  Another possibility is that knife itself is getting executed with odd locale settings.

Can you perhaps determine what those early bytes in the file are?  If you have access to the unix hexdump utility, something like `hexump -C FILENAME` might help.

**Comment by swade1987** [comment]
Unfortunately I don't have access to that as I am running on a Windows machine.

**Comment by stevendanna** [comment]
@swade1987 Here are some other possible diagnostic steps:

- Create an environment file using a text editor and ensure you can upload it with `knife environment from file`

- Ensure that the environment you are getting back from the API is correct.  For instance, does the following work (note, this redirects standard output, you may need to translate these to the equivalent windows command):

    knife raw /environments/prod > prod.json
    knife environment from file prod.json

Replacing prod with the name of your environment.  If this works, it is likely something in your editing process that is introducing the encoding/characterset problem.

Note that I think using knife raw rather than `knife environment show` will be better for your use case. The output of `knife environment show ENV_NAME -F json` appears to exclude the "name" field which is necessary to POST it back to the API.

> Unfortunately I don't have access to that as I am running on a Windows machine.

I believe there are other hexdump like utilities for window; but I can't recommend any as I haven't used them.  If you would like, you can email me the file (steve@chef.io) and I can take a look; however, it could easily get mangled by your email client or mine.

While I am happy to help you, you may get a quicker response by trying the mailing list or our support channel (support@chef.io).  I typically check Github issues across a number of projects once a day.

**Comment by stevendanna** [comment]
@swade1987 Is this still an issue for you?

**Comment by swade1987** [comment]
Happy for this to be closed now.


Regards


Steve


------------------------------------
Steven Wade

Principal Consultant

Steven Wade Consulting Ltd

077 3822 1296

steven@stevenwade.co.uk<mailto:steven@stevenwade.co.uk>

https://www.linkedin.com/in/stevendavidwade?

________________________________
