### ISSUE TITLE
Support for AWS V4 Signature (Frankfurt region)

### ISSUE THREAD

**Issue by abriel** [chef/chef-server#1013]
Hello,

As you know we can use s3 bucket instead of embedded bookshelf service.
Then erchef generates signed url and returns it to knife, so we can upload or download cookbook files directly from s3.
But new region of AWS - Frankfurt supports only the latest signature version: AWS4-HMAC-SHA256. Which is not supported by chef-server or lack of documentation.
When I do upload of cookbook, I got the following (from s3 with an url given me by chef-server) :
`<Error><Code>InvalidRequest</Code><Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message>`.

Unfortunately we still use 11.x version and can't move to 12.x right now.
I don't know if it applies to 12.x version. I tried 11.1.7, the latest if available from https://downloads.chef.io/chef-server/redhat/ .

Thanks.

**Comment by codeadict** [comment]
is this still needed?

**Comment by abriel** [comment]
We found a workaround by using S3 bucket belongs to another region, which still supports V2.
So now depends on your wish.. Thanks.

**Comment by codeadict** [comment]
cool, i may work on it :)

**Comment by runningman84** [comment]
any news here?

**Comment by codeadict** [comment]
I have it running locally, need to write tests and dedicate some time to it this week, have been sidetracked with work

**Comment by stevendanna** [comment]
Awesome to hear @codeadict.  Feel free to reach out if there is anything we can help with.

**Comment by alokdnb** [comment]
@codeadict, are you still doing testing and planning to submit PR?

**Comment by markan** [comment]
We're going to have to take this on soon.  June 24, 2019 is the EoL date for V2 signing (https://forums.aws.amazon.com/ann.jspa?annID=5816)

**Comment by markan** [comment]
We've demoted this in priority because AWS has delayed the cutover
https://aws.amazon.com/blogs/aws/amazon-s3-update-sigv2-deprecation-period-extended-modified/

We originally had targeted it for the Chef Server 13.0 release, (and had done substantial work to update mini_s3 to support that, see the ma/v4_signing branch and the chef-server ma/aws_v4_signing       
 branches), but with this news we're delaying a little bit.

AWS V4 signing is a bit more complex than V2, and rather than carry our own implementation, it would be better to use an external mainstream library. At a quick glance the libraries out there either require a newer version of Erlang/OTP than R18, or seem to trigger a conflict with some of our transitive deps (erlware_commons in particular). 

The mini_s3 update was pursued because it was perceived to be lower risk and time than updating OTP and a large swath of our dependencies. However, with this reprieve we can do the right thing and update OTP and our dependencies. This will produce a more maintainable system. We should be able to tackle this soon after CS 13.0 is released.

Two candidates to examine are: 
* https://github.com/erlcloud/erlcloud
* https://github.com/aws-beam/aws-erlang

This work has a couple of components:
1) Decide if we're going to support v2 & v4, or just v4. If we only want to support v4 we have to update bookshelf to accept v4 signed requests. However if we support both, we may have some problems because the above libraries seem to be v4 only, and mini_s3 might need to be retained.
2) Replace or wrap mini_s3 to use V4 signing. Theres a little bit of an impedance mismatch between the above libraries and mini_s3's api, so some work will be required either way. One important thing is we generate pre-signed URLs in a special way to help nginx caching. (We round off the timestamps to discrete intervals so that multiple requests for the same object in a narrow window of time end up with the same URL, making that cacheable.)
3) Update chef-server oc_erchef to use v4 signing (see ma/aws_v4_signing for a little work on that)
4) Either support v2 signing, or update bookshelf (our s3 clone) to support v4.

**Comment by codeadict** [comment]
That is a a good plan, i've used erlcloud quite a bit and is very well maintained.

**Comment by PrajaktaPurohit** [comment]
closing in favor of #1783
