### ISSUE TITLE
Not able to create user after reconfiguring

### ISSUE THREAD

**Issue by milindjain12** [chef/chef-server#1236]
I am using CentOS 6.6 machine and trying to install stand-alone chef 12.14.0-1 server. 
I changed the port in the chef-server.rb file as on my machine Apache2 is also running but after that when I reconfigure the server and try to create user on server it is giving the following error.

ERROR: Failed to authenticate to https://127.0.0.1:10443 as pivotal with key /tmp/latovip20170419-16754-1rpfa05
Response:  Invalid signature for user or client 'pivotal'

I am able to figure out how to solve this error.
Following is the content of the chef-server.rb file :

nginx['non_ssl_port']=10080
nginx['ssl_port']=10443
nginx['url']="https://mphasischef:10443/"

It will be great if I get a solution for that ASAP.

Thanks

**Comment by cheeseplus** [comment]
The problem here most likely was `nginx['url']` including the port which it's not supposed to as that's defined elswhere and composed by the things that need it. It's also highly inadvisable to be running another webserver next to the nginx chef-server runs - we recommend treating chef-server more like an appliance and giving it a full virtual machine or physical box.
