### ISSUE TITLE
Create Docker environment for local development

### ISSUE THREAD

**Issue by codeadict** [chef/chef-server#1291]
The actual development server using Vagrant works pretty good but i think that having a Docker based Development environment can be simpler and leaner for the dev machine. Will be nice to orchestrate the server locally using Docker compose.

**Comment by stevendanna** [comment]
I go back and forth.  The current development environment suits our needs, but Chef Server doesn't get many new developers that often so we have a lot of survivor bias (everyone who works on Chef Server knows how to work around various problems).  

In the future, I could see a world in which a docker-based environment makes more sense, especially as more and more of our users move to an "external ES + external Postgres" setup You could run the applications services in container (or a set of containers) and then point them at ES and postgresql containers and theoretically not be too far from what customers are actually deploying.

However, a problem we've seen with other docker-based dev setups we have is that the actual installation and configuration of the application ends up being very different since we are still tied to `chef-server-ctl reconfigure` for the foreseeable future.  Most bugs people hit in Chef Server these days are actually problems in the underlying cookbooks.  Thus, iterating on those cookbooks tends to be the most important thing to optimize the development environment for and I'm not sure there is a clean way to do that in a docker-compose environment.

**Comment by PrajaktaPurohit** [comment]
@codeadict Sorry for the late reply on this. At this time we do not support chef-server on docker because it does not run well in that environment. A dev environment would have the same problem and be very different from how Chef Infra Server is deployed, leading to problems. Closing this issue for now. But Pull Requests are always welcome :)
