### ISSUE TITLE
chef-backend-crashing

### ISSUE THREAD

**Issue by zimmma00** [chef/chef-server#1405]
## Current Behavior

My organization has moved to chef HA.  We are running 3 chef backend servers.  They are running on virtual machines.  And this is our development environment.  After a couple of weeks the chef servers crash.  To get them back, we have to recycle all the backend servers.  When we get into this situation, here is the some of the output.

Service        Local Status         Time in State   Distributed Node Status                                  
leaderl        running (pid 22080)  27d 9h 51m 38s  leader: 0; waiting: 3; follower: 0; total: 3             
epmd           running (pid 22135)  27d 9h 51m 37s  status: local-only                                       
etcd           running (pid 22137)  27d 9h 51m 37s  health: green; healthy nodes: 3/3                        
postgresql     down                 0d 0h 10m 27s   error: could not reach pgsql leader for replication stats
elasticsearch  running (pid 5758)   7d 10h 30m 21s  state: green; nodes online: 3/3                          

System  Local Status                                          Distributed Node Status          
disks   /var/log/chef-backend: OK; /var/opt/chef-backend: OK  health: green; healthy nodes: 3/3

And all the servers are waiting someone to become the leader.  We have all followers.

What do I need to fix the issue?  What do I need to do the next time this occurs to gather information?

## Steps to Reproduce (for bugs)

1. It just seems like time for us.  Not sure why.  That is where I need the help.

## Your Environment

* Chef Server Version: chef-backend-1.4.6-1.el7.x86_64
* Total/free RAM and disk space: RAM - 8 GB disk - nothing that looks like it is out of space
* Operating System and Version: Oracle Linux Server release 7.3
* If upgrading, previous Chef Server version:
* Running in a container?

**Comment by stevendanna** [comment]
Hi,

> To get them back, we have to recycle all the backend servers.

By recycle the leader do you mean that you rebuild them all?  If so, Have you tried `chef-backend-ctl force-leader` on the previous leader node instead?

In terms of the root cause, your best bet is to open a support ticket when they go down next time.  (This is the bug tracker for open source chef-server. Chef Backend is a commercial product that is supported via Chef Support).

That said, the first step would be to figure out why they are getting into the waiting for leader state.  The log for the leaderl service is in `/var/log/chef-backend/leaderl/current`.  Unfortunately, this log can be very noisy.  

There is also the `chef-backend-ctl gather-logs` command that will put together a tarball of logs and other data that can help diagnose the issue.

I can tell you hat the main causes we see for failure of chef-backend current is related to disk performance.  `etcd`, the underlying consensus system seems very sensitive to increased disk latency.  The gather-logs output includes output from the etcd stats endpoint that can help diagnose that as well.

**Comment by zimmma00** [comment]
Thank you for the quick response.  I will open the ticket with chef support.  I also appreciate all the information that you gave me.
