### ISSUE TITLE
chef-server does not respect server_name set in chef-server.rb

### ISSUE THREAD

**Issue by luckymike** [chef/chef-server#144]
On an Amazon VPC instance in a VPC with EnableDNSHostnames turned off, the the Chef Server nginx config is generated with `server_name ;` on lines 88 and 120. This causes NGINX to fail. 

We had set `nginx['server_name'] = <elb-address>` in `/etc/opscode/chef-server.rb`, but that value does not seem to be picked up.

**Comment by sean-horn** [comment]
Hi,

Part of the prereqs are that the system has a resolvable `hostname` and `hostname -f` and that those should match.  http://docs.chef.io/install_server_pre.html#hostnames

Ohai uses those to gather the FQDN for the system and then the embedded chef server cookbooks come along and use that data as the nginx `server_name` on a system with no customized `/etc/opscode/chef-server.rb`

If you set `api_fqdn` in `/etc/opscode/chef-server.rb`, that should also work, otherwise, it defaults to the Ohai gathered FQDN.

**Comment by james-s-nduka** [comment]
^ This will resolve it :+1: 
However if you do not want to set the `api_fqdn` Ensure the hostname has been set and you have updated the "/etc/hosts" file on the EC2 instance.
Lastly run "chef-server-ctl reconfigure" for the changes to reflect in the NGINX config.

**Comment by luckymike** [comment]
Somehow I missed @sean-horn's comment, though I'd already sorted things out. I believe the issue I ultimately needed to resolve had to do with the `nginx[server_name]` character limit. For posterity:

If you're using an elb in front of your Chef Server, be sure to name that ELB, because it's auto-generated name will be too long. :)
