### ISSUE TITLE
API Endpoint "keys" delete method not allowed (405)

### ISSUE THREAD

**Issue by ezequiels** [chef/chef-server#1471]
![screen shot 2018-02-13 at 2 11 00 pm](https://user-images.githubusercontent.com/10506207/36171314-c3052852-10c7-11e8-89ca-8e456fdcfb7a.png)
## Expected Behavior

documentation for the 'knife exec' states that using knife exec and the desired api method we should be able to accomplish plenty of tasks.
Documentation for the chef api shows that the endpoint /users/USER/keys/KEY has the following methods available (GET, PUT, DELETE)

I'd expect to be able to delete an ssh key by executing:

knife exec -E 'puts api.delete("users/USER/keys/key")'

## Current Behavior

when executing the command I receive the following error:

ERROR: Method Not Allowed
Response: <html><head><title>405 Method Not Allowed</title></head><body><h1>Method Not Allowed</h1>Method Not Allowed<p><hr><address>mochiweb+webmachine web server</address></body></html>

## Steps to Reproduce (for bugs)

1. first ensure you have a key for a user by using:

```knife exec -E "puts api.get('users/USER/keys')"```

you should see a list of keys

2. Try to delete the key by using the name of the key:

```knife exec -E "puts api.delete('users/USER/keys/KEY')"```

the key won't be deleted and the error shown is:
```
ERROR: Method Not Allowed
Response: <html><head><title>405 Method Not Allowed</title></head><body><h1>Method Not Allowed</h1>Method Not Allowed<p><hr><address>mochiweb+webmachine web server</address></body></html>```


## Your Environment

* Chef Server Version: 12.17.15
* Total/free RAM and disk space: 16gb, 6GB
* Operating System and Version: RHEL 7.4
* If upgrading, previous Chef Server version:
* Running in a container? No

**Comment by markan** [comment]
It appears that we only implemented 'GET' for user keys. See: https://github.com/chef/chef-server/blob/master/src/oc_erchef/apps/oc_chef_wm/src/oc_chef_wm_named_key.erl#L71, we seem to have skipped that. I'm not sure why; it seems like an oversight, and a missing piece for full functionality.

**Comment by jashaik** [comment]
After allowing the 'DELETE' method in oc_erchef, user is able to delete the named keys using knife tool but the same is failing in the pedant tests.
 
Allow DELETE method - https://github.com/chef/chef-server/commit/c1aa9768bc4964aa81b425eac2da814bbe6f218f
Pedant test - https://github.com/chef/chef-server/compare/shahid/key-delete-api#diff-70f9e095036d84cdf45878f96c0a2fc22eaef82a2c94ef57bce8422a3b4c62d0
Pipeline result - https://buildkite.com/chef/chef-chef-server-master-omnibus-adhoc/builds/1985#3cef946c-844e-43e3-8895-aba23076d4ae

After discussion with @PrajaktaPurohit , the change is not as straightforward as it seems for a couple of reasons users are independent of orgs , there isn't a notion of using a key for user from only within the orgs. so while it should be ok to perform the necessary rest operations /user/username/key/keyname it might not be the right thing to do for /org/orgname/user/username/key/keyname.It appears that this might be happening due to knife not being able to differentiate between those paths.

Knife Working Screenshot -
![Screenshot 2020-12-31 at 12 23 58 PM](https://user-images.githubusercontent.com/76031665/105502432-71212680-5ceb-11eb-8e2e-e311308cbfce.png)

Pedant Failing with bad signature -
![Screenshot 2021-01-22 at 8 01 58 PM](https://user-images.githubusercontent.com/76031665/105503547-bd209b00-5cec-11eb-83ab-baa367bdf387.png)

**Comment by PrajaktaPurohit** [comment]
@ezequiels Thank you for creating this issue. Looks like you are trying to delete the user's default key, that operation is not permitted. https://github.com/chef/chef-server/issues/2240 tracks updating the docs with that info.

For operating against the global end point like the /users endpoint our recommendation is to use commands like
```
** USER COMMANDS **
knife user create USERNAME DISPLAY_NAME FIRST_NAME LAST_NAME EMAIL PASSWORD (options)
knife user delete USER (options)
knife user edit USER (options)
knife user key create USER (options)
knife user key delete USER KEYNAME (options)
knife user key edit USER KEYNAME (options)
knife user key list USER (options)
knife user key show USER KEYNAME (options)
knife user list (options)
knife user reregister USER (options)
knife user show USER (options)
```

In this particular case `knife user key delete username keyname(other than default)` knows to hit the global /user end point rather than in the context of an org like /organizations/orgname/users.

Although looking at the code it may seem like adding support to the DELETE method is all that we need to do, in terms of the context, it would mean that a user key can be deleted within a reference of an org. That could cause some unwanted side-effects since a user's key is a global object that can exist outside of an org.

If you need to use the `knife exec` command for automation, a workaround that can be used is updating the chef_server_url in knife.rb to http://hostname instead of http://hostname/organizations/orgname/

Or if you wanted to delete any user key other than default from the command line:
```
root@api:/vagrant# knife exec -E 'api.delete("/users/myuser/keys/user33")' --server-url https://<hostname>
```

Closing this issue for now. Please feel free to reopen or open a new issue if the workarounds do not work fo you.
