### ISSUE TITLE
API Endpoint containers/containers returns method not allowed (405)

### ISSUE THREAD

**Issue by vsingh-msys** [chef/chef-server#1613]
### Chef Server Version
12.18.14

### Platform Details
Ubuntu 16.04(Vagrant VM)

### Configuration
API request on chef server 
```
Chef server Url: https://chef-server3.test/organizations/organization-name
API path: containers/containers
JSON data: {"containername"=>"containers", "containerpath"=>"containers"}
API Version: "0"
```
### Scenario:
Try to upload the containers using the following commands
```
knife upload /containers --purge --force  --repo-mode hosted_everything
```
But getting the Method not allowed(405) error.

### Steps to Reproduce:

Setup standalone chef-server 12.18.14 and create organization and user.
configure knife and download all data from chef server using:
```
knife download / --chef-repo-path /app/chef-repo --repo-mode hosted_everything
```
Now try to upload the all or containers related data by using:
```
knife upload / --purge --force --chef-repo-path /app/chef-repo --repo-mode hosted_everything
OR
knife upload /containers --force
```
But getting `HTTP error writing: 405 "Method Not Allowed"` error.

### Expected Result:
It should update all containers recourses (groups, environments, nodes etc).

### Actual Result:
```
ERROR: containers/environments.json failed to write: HTTP error writing: 405 "Method Not Allowed"
ERROR: containers/groups.json failed to write: HTTP error writing: 405 "Method Not Allowed"
ERROR: containers/nodes.json failed to write: HTTP error writing: 405 "Method Not Allowed"
ERROR: containers/policies.json failed to write: HTTP error writing: 405 "Method Not Allowed"
ERROR: containers/policy_groups.json failed to write: HTTP error writing: 405 "Method Not Allowed"
ERROR: containers/roles.json failed to write: HTTP error writing: 405 "Method Not Allowed"
ERROR: containers/sandboxes.json failed to write: HTTP error writing: 405 "Method Not Allowed"
```
### Chef server logs
```
==> /var/log/opscode/nginx/access.log <==
192.168.33.1 - - [2019-01-24T14:21:52+00:00]  "PUT /organizations/4thcoffee/containers/containers HTTP/1.1" 405 "0.006" 177 "-" "Chef Knife/15.0.140 (ruby-2.5.3-p105; ohai-15.0.26; x86_64-linux; +https://chef.io)" "127.0.0.1:8000" "405" "0.002" "15.0.140" "algorithm=sha1;version=1.1;" "delivery" "2019-01-24T14:21:55Z" "A/GhYWE5CvT8HSiwYkL8Dw6NhWQ=" 1165 "ed3a687d-410f-400e-af76-2aeba0a13300"

==> /var/log/opscode/opscode-erchef/requests.log.1 <==
2019-01-24T14:21:52Z erchef@127.0.0.1 method=PUT; path=/organizations/4thcoffee/containers/containers; status=405; req_id=g3IAA2QAEGVyY2hlZkAxMjcuMC4wLjEBAAIyZAAMAAEAAAAA; org_name=4thcoffee; couchdb_groups=false; couchdb_organizations=false; couchdb_containers=false; couchdb_acls=false; 503_mode=false; couchdb_associations=false; couchdb_association_requests=false; req_time=0; user=delivery; req_api_version=0;
```
Reference issue: https://github.com/chef/chef/issues/7949

**Comment by markan** [comment]
The workaround is you can POST to the containers endpoint if you really need to manipulate the container. Even that probably shouldn't exist; DELETE is even worse in that you can seriously break the system using it.

In general, it's probably not a good idea to do much creation (or even worse, deletion) of containers.
* First, containers are really only things to hang ACLs off of; they have no other internal state.
* Second, they are created by the org creation code, so they should all exist and not need creation as part of a restore. The ACLs for the container might change, and need restoring, but the containers themselves should always exist.
* Third, they are entangled with the first class objects available on the system. A 'nodes' container exists because there's an object called a 'node' and we want to manage default permissions for it. Creating a 'foo' container without a 'foo' object being implemented would do nothing, and probably is an error. If you are downgrading (for example migrating from a chef-server version with policyfiles and associated containers to one without) copying the container over wouldn't help you much; it wouldn't do anything, and most likely would be overwritten if you upgraded that server.

**Comment by markan** [comment]
I'm leaving this open for a little while, in case I've missed some important use case, but this probably should be closed otherwise.

**Comment by vsingh-msys** [comment]
As of now, we don't require these features. Reference https://github.com/chef/chef/issues/7949
If yes we will open this issue.
Thanks
