### ISSUE TITLE
Provide a way to disable Ohai plugins (e.g. passwd) during `chef-server-ctl reconfigure`

### ISSUE THREAD

**Issue by jerryaldrichiii** [chef/chef-server#1638]
### Describe the Enhancement:

In large enterprises Ohai can hang when fetching users from AD. Since Ohai runs when doing a `chef-server-ctl reconfigure` this can make installation not possible (or...take waaaaay too long).

### Current Alternative

Disabling the connection to AD on the server.

**Comment by tas50** [comment]
We should probably run minimal ohai for the chef run in the server. There's no need to fetch all that extra data for an embedded chef-client run.

**Comment by markan** [comment]
This looks pretty straightforward to fix. We're running chef here I think:
https://github.com/chef/omnibus-ctl/blob/e160156deaa0afc037748b10d1c9ef0a5be97dc1/lib/omnibus-ctl.rb#L490

The solo.rb is being rendered here:
https://github.com/chef/chef-server/blob/master/omnibus/config/software/private-chef-cookbooks.rb#L61

There is a possible snag because we also run chef from here: https://github.com/chef/chef-server/blob/master/omnibus/files/private-chef-cookbooks/private-chef/resources/chef_run.rb#L39
And we should check that that is also using the config.

**Comment by markan** [comment]
Also, forgot to mention that a newer version of ohai would help, as we've pruned the default list enormously.

**Comment by jerryaldrichiii** [comment]
Closing this as I do not support Chef's contract with ICE and no longer care about the result of this ticket.
