### ISSUE TITLE
2. Expand terraform to work across the matrix of distributions.

### ISSUE THREAD

**Issue by PrajaktaPurohit** [chef/chef-server#1778]
The testing for Chef-Infra-Server before release should be run across all the supported distributions.

- Redhat Enterprise Linux 6
- Redhat Enterprise Linux 7
- ~SUSE Linux Enterprise Server 11~ (no longer supported)
- SUSE Linux Enterprise Server 12
- Ubuntu 16.04
- Ubuntu 18.04

We currently have 2 scenarios working for testing on an adhoc basis:
1. standalone upgrade
2. tiered fresh install ipv6

To Test:
If we launch the same scenario with different versions of artifact to be tested, it creates multiple instances in ec2. 
Would running make destroy for a scenario, destroy then all?

**Comment by christopher-snapp** [comment]
@PrajaktaPurohit,

I've opened PR #1791 to enable concurrent testing across the matrix of distributions as well as IPv4 vs IPv6.

In reviewing this issue I'm seeing your "To Test" section describing a situation where someone would be testing the same scenario multiple times concurrently specifying different artifact versions.  This seems like an odd situation because I would have expected the focus of testing to be on an artifact related to the current git working tree.  If this is a realistic scenario, I'll have to further expand the workspace naming to accommodate both versions to ensure uniqueness.

**Comment by PrajaktaPurohit** [comment]
Closing this since we now support running a version on multiple distributions. (#1791) Will create another issue to track being able to run multiple upgrade versions on multiple distributions.
