### ISSUE TITLE
`cleanse` command doesn't delete the upstart file 

### ISSUE THREAD

**Issue by stevendanna** [chef/chef-server#179]
From @jeremiahsnapp in chef/opscode-omnibus#729:

> The chef-server-ctl cleanse command in Chef Server 12 doesn't delete the upstart file because it's looking for /etc/init/chef-server-runsvdir.conf when the file is actually still named /etc/init/private-chef-runsvdir.conf.
> 
> https://github.com/chef/omnibus-ctl/blob/master/lib/omnibus-ctl.rb#L223

**Comment by smith** [comment]
IMO removing these files should be handled by the [enterprise cookbook](https://github.com/opscode-cookbooks/enterprise-chef-common), since that cookbook is responsible for creating them. There are all kinds of bugs around this, especially between specially-named packages and differences between init systems, which aren't going to get any better.

I'm going to be doing some work on this as part of the reconfigure step for Manage, but not sure how this directly affects this issue.

**Comment by PrajaktaPurohit** [comment]
Closing this for now. Please reopen is the issue persists.
