### ISSUE TITLE
Upgrade ignores port settings in chef-server.rb

### ISSUE THREAD

**Issue by tomhughes** [chef/chef-server#212]
I have the chef server configured, in `/etc/chef-server/chef-server.rb`, to start on non standard ports:

```
nginx['non_ssl_port'] = 4000
nginx['ssl_port'] = 4443
```

but when upgrading from chef server 11 to 12 this is ignored, and `chef-server-ctl upgrade` tries to start nginx on the default ports, which fails as apache is already listening there.

**Comment by SeanSith** [comment]
Ran across a similar problem tonight myself. Look in /etc/opscode for the new location of your chef-server.rb. Documentation isn't clear anywhere.

**Comment by mmzyk** [comment]
@tomhughes @SeanSith is right. Chef server 12 is based on the Enterprise Chef codebase and still uses the old Enterprise code paths with opscode in the name. The plan is to eventually replace opscode with chef-server in these paths, but this was not done initially so that we could enable the side-by-side upgrade path, since the open source Chef server 11 used the chef-server paths.

We clearly missed documenting this change well enough. I'll get a noted added to the docs to try and make this clearer. Thanks to both of you for bringing this up.

I am going to close this issue out, since these settings are respected if you put the chef-server.rb in the right place, and then I'll take it as a todo to get the docs updated.
