### ISSUE TITLE
How do we manage the security updates of the embedded components? specifically in my case, it's JRE.

### ISSUE THREAD

**Issue by qudongfang** [chef/chef-server#2223]
How do we manage the security updates of the embedded components? specifically in my case, it's JRE.

- version: chef-server-core-14.0.65-1.el7.x86_64.rpm
- os: CentOS

Due to compliance restrictions, we need to constantly resolve vulnerabilities found.

We ran into some critical vulnerabilities with an older version in the beginning, and then I upgraded it to the latest stable version.

The JRE bundled with the latest stable chef-server has 2 Medium vulnerabilities(which seems not very serious)

Here are the details of one:

> Risk Information
> Risk Factor: Medium
> STIG Severity: I
> Vulnerability Priority Rating: 7.3
> CVSS v2 Base Score: 5.8
> CVSS v2 Temporal Score: 4.3
> CVSS v2 Vector: AV:N/AC:M/Au:N/C:P/I:P/A:N/E:U/RL:OF/RC:C
> CVSS v3 Base Score: 4.8
> CVSS v3 Temporal Score: 4.2
> CVSS v3 Vector: AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:N/E:U/RL:O/RC:C

I found that we allow users to choose external components sometimes, namely PostgreSQL and ElasticSearch at the moment.
It would be great to me if we could do this for the JRE/JDK. (and I don't see the rationale why not, It appears to me that JDK is only required by ElasticSearch, please correct me if I'm wrong.)
 

**New vulnerabilities will constantly pop up in the future, I wonder what's the process/principle of general to manage them?**

Any suggestions would be greatly appreciated!

https://github.com/chef/chef-server/issues/2219

**Comment by tas50** [comment]
@qudongfang We have a release planned for early Feb that will include the latest release of openJDK 11. We're working to track the openJDK releases and ensure that we pull those into our end to end testing pipeline so we can quickly push releases of the product that have been validated for these new versions.

**Comment by qudongfang** [comment]
> @qudongfang We have a release planned for early Feb that will include the latest release of openJDK 11. We're working to track the openJDK releases and ensure that we pull those into our end to end testing pipeline so we can quickly push releases of the product that have been validated for these new versions.

@tas50 Thanks for the good news about the coming release!
Not only the OpenJDK issues

It would be great if you cloud share how does Chef resolve/manage these kinds of security issues, for example, how long can we/customers expect the security issues to be patched?
Not only the OpenJDK related but also all the embedded components, like ruby, erlang, etc?

The security issues are something we need to deal with for the long term, they'll keep coming for certain.

**Comment by tas50** [comment]
@qudongfang I wanted to circle back to this issue and give you a definite plan for how we see our response to security issues going forward within Chef Infra Server.

First, it's important to give a bit of historical context as to why it's taken a while to release fixes in the past. Historically we've made just a few releases of Infra Server a year due to the large amount of manual validation required before a release can be made. This was several weeks of engineering time spent validating the various ways the Infra Server could be configured in environments. The long validation cycle made it impractical to release more than just a few times a year, which delayed the release of updated components with CVE fixes. 

Over the last year we've expanded the Infra Server team, and this team along with our end-to-end testing team has invested heavily in automating our release validation process. We have a mostly automate validation process at this point which is allowing us to commit to far more frequent releases of Infra Server going forward. The goal for 2021 onward is to release each new feature or component upgrade as they become available. Chef Infra Server 14.1 was the first release of this new process. It featured security updates to OpenSSL, Nokogiri, Ruby, and OpenJDK as well as some smaller improvements to the server application itself. 

We expect to see a 14.2 release shortly as we ready updates to other components within the stack. We currently have work underway to update Elasticsearch, Postgresql, and Rails to the latest releases. As development on those individual updates completes we will ship new versions so we can get that code to customers as soon as possible. Long term the goal is to keep these components more up-to-date utilizing our improved validation automation, but there's a bit of a backlog of updates for the team at the moment. We'll continue to prioritize releases to components like OpenSSL, Ruby, and OpenJDK since the development work involved there is pretty minimal. That should allow us to keep those components CVE free.

Hopefully that helps with the concerns you've had. TLDR here is we hope to make rapid releases as CVEs pop up going forward. It just took some work to get to the point where that was possible.
