### ISSUE TITLE
Update the version of chef-server in Automate

### ISSUE THREAD

**Issue by lbakerchef** [chef/chef-server#2652]
Latest greatest is 14.6.32.

https://github.com/chef/automate/issues/5371

**Comment by PrajaktaPurohit** [comment]
https://github.com/chef/chef-server/pull/2775

**Comment by jashaik** [comment]
14.9.23 release should resolve all the chef-server issues in Automate environment. Yet to create a PR in automate.

**Comment by vinay-satish** [comment]
There are two  PR created in the automate repository. Each PR is pointing to two different channels in the habitat builder.
Since the automate will no longer will not be using stable channel, the PR https://github.com/chef/automate/pull/5726 is closed.
Automate will be using the new refresh channels for it deployment. The PR pointing to refresh channel is - https://github.com/chef/automate/pull/5772

**Comment by PrajaktaPurohit** [comment]
Blocked. Currently fails in dependency resolution for core/glibc and core/linux-headers. https://buildkite.com/chef/chef-automate-main-verify-private/builds/18338#8564bacc-6dce-4457-a01a-3de0f5282a6a/689-1048

**Comment by vinay-satish** [comment]
Also as part of this, we need to add `--skip=headers` while running pedant. https://github.com/chef/chef-server/pull/2815#discussion_r730586966

**Comment by vinay-satish** [comment]
The latest chef-server has the pg13, but automate is still not updated yet. The changes for the current latest 14.10.23 are ready in the PR - https://github.com/chef/automate/pull/6183

**Comment by vinay-satish** [comment]
1. Dependencies issue - The automate component dependencies were moved to `stable2021-q2` from `stable` channel of the habitat. chef-server component dependencies were still using `stable` channel, because of this we had the dependency issue.
2. The automate pipeline is failing because the erchef and nginx components are CRITICAL, but working in dev environment.
2. Data collector issue - The data_collector is enabled Automatically in the automate-cs-oc-erchef but the URL is not working so CS is sending the status as  fail due to CS is not able to send the data to the defined URL in configuration. We can disable the data collector.
3. chef-server-ctl issue - We are not able to run `chef-server-ctl` commands in the dev environment. getting the following error - `Could not find rake-13.0.6 in any of the sources
Run bundle install' to install missing gems.`. Bundle install is failing with the error `bash: bundle: command not found`.

**Comment by jashaik** [comment]
Status -
Upgrade migration is failing in the automate after updating the CS version.
Pipeline - https://buildkite.com/chef/chef-automate-main-verify-private/builds/19525#054129b7-9376-4041-9da3-d68d39d8ac1b 

```
This is failing with sqitch error.
Dec 10 06:51:00 a1-migration.test hab[4747]: pg-sidecar-service.default(O): Cannot find change 4168bd129204d3c9137179a5e52173ffa07476bc (cookbook_versions_cookbook_id_index @1.0.4) in /hab/pkgs/chef/oc_erchef/14.11.1/20211124104838/schema/baseline/sqitch.plan
Dec 10 06:51:00 a1-migration.test hab[4747]: automate-pg-gateway.default(O): 127.0.0.1:36610 [10/Dec/2021:06:51:00.380] postgresql automate_postgresql/127.0.0.1 1/0/29 4488 SD 65/65/64/64/0 0/0
Dec 10 06:51:00 a1-migration.test hab[4747]: pg-sidecar-service.default(O): time="2021-12-10T06:51:00Z" level=error msg="failed to deploy sqitch" action=deploy_sqitch conn_info="postgresql://automate@127.0.0.1:10145/<database>?sslmode=verify-ca&sslcert=/hab/svc/automate-postgresql/config/server.crt&sslkey=/hab/svc/automate-postgresql/config/server.key&sslrootcert=/hab/svc/automate-postgresql/config/root.crt" db=automate-cs-oc-erchef db_database=postgres error="exit status 2" sqitch_dir=/hab/pkgs/chef/oc_erchef/14.11.1/20211124104838/schema/baseline user=automate

```
These are not creating the issues in the fresh install but failing in the upgrade It seems.
need investigate more on this.

**Comment by jashaik** [comment]
https://github.com/chef/automate/pull/6183
