### ISSUE TITLE
Make oc-id work with dvm

### ISSUE THREAD

**Issue by smith** [chef/chef-server#299]
Chef server has a built-in [development environment](https://github.com/chef/chef-server/tree/master/dev) that we should use instead of opscode-dev-vm. It can do code loading like dev-vm, but currently doesn't do that for oc-id. Make it do that.

**Comment by marcparadise** [comment]
I'm happy to make that happen but would need to work with someone who can help me out understanding how it runs, etc. I'll be on-site first week in june, we could do it then?

**Comment by mmzyk** [comment]
@marcparadise by on site you mean in Seattle? Most of Team VI lives else where, but @cnunciato can probably help out in person, since he is back in Seattle. I'll also be in Seattle as well. Not a lot of mystery with oc-id - it's a pretty straight forward Rails app.

**Comment by marcparadise** [comment]
Yep, Seattle‎. I can probably find what I need just looking at the runit script, but it'll be easier to have someone more familiar than I with Rails apps on hand.                                                                                                                                                                                                                  From: Mark MzykSent: Tuesday, May 26, 2015 5:23 PMTo: chef/chef-serverReply To: chef/chef-serverCc: Marc A. ParadiseSubject: Re: [chef-server] Make oc-id work with dvm (#299)@marcparadise by on site you mean in Seattle? Most of Team VI lives else where, but @cnunciato can probably help out in person, since he is back in Seattle. I'll also be in Seattle as well. Not a lot of mystery with oc-id - it's a pretty straight forward Rails app.

—Reply to this email directly or view it on GitHub.

**Comment by PrajaktaPurohit** [comment]
oc-id does work with dev env! Please reopen if it does not.
