### ISSUE TITLE
opscode-expander-reindexer can likely be removed

### ISSUE THREAD

**Issue by stevendanna** [chef/chef-server#30]
`opscode-expander-reindexer`'s intended purpose was for reindexing the entire Chef Server.  In theory you would do this:

1. Turn off opscode-expander
2. Run a reindex tool which sends all updates to the /reindex rabbitmq vhost which is read by opscode-expander-reindexer.
3. Once the reindex is complete, restart opscode-expander, processing writes that have come in since step (1).

However, with the erchef rewrite, we no longer have a tool that does (2).  Further, it is likely that if we were to write a installation-wide reindex tool, it would be the moral equivalent of:

```
SAFTEY_TIMER=30
for org in $(chef-server-ctl org-list); do
   redis-cli HSET dl_org_$org 503_mode true
   sleep $SAFTEY_TIMER
   /opt/opscode/embedded/service/opscode-erchef/bin/reindex-opc-organization complete $org
   redis-cli HDEL dl_org_$org 503_mode
done
```

We might consider removing this component from the chef-server as there is *nothing* that currently uses it.

**Comment by sdelano** [comment]
+1. In addition, with the migration to Solr 4+, we no longer even **need** the async RabbitMQ -> Expander bits of the infrastructure.

These were in place primarily because Solr 1.3 blocked when issuing a commit to disk, and Solr 4 no longer behaves this way. The async posts to Solr allowed requests to proceed without waiting on Solr, but also resulted in a ~1 minute "save until searchable" behavior where your saves weren't searchable for up to a minute (or longer depending on load).
