### ISSUE TITLE
Multiple version constraints for the same platform in metadata.rb ignored

### ISSUE THREAD

**Issue by ghost** [chef/chef-server#31]
I'm referring to [bug #2457 in chef-client](https://github.com/opscode/chef/issues/2457)

Consider the following "platform constraints" in metadata.rb or Cookbook „example“

``` ruby
supports 'redhat', '~> 6.5'
supports 'redhat', '~> 7.0'
supports 'centos', '~> 6.5'
supports 'centos', '~> 7.0'
```

This actually leads to the following merge:

``` ruby
# run_context.cookbook_collection['example'].metadata.platforms

@platforms={"redhat"=>"~> 7.0", "centos"=>"~> 7.0"}
```

It's obvious why this i happening. I'd have been exspecting something like this:

``` ruby
@platforms={"redhat"=> ["~> 6.5", "~> 7.0"], "centos"=> ["~> 6.5", "~> 7.0"]}
```

Unfortunately this would introduce a breaking change.

Also there's a [related bug](https://tickets.opscode.com/browse/CHEF-4727) which could be fixed with a similar approach.

I'd like to help - but I'm not sure which notation would be best.

Should we use:

``` ruby
supports 'centos', '~> 6.5'
supports 'centos', '~> 7.0'
```

or

``` ruby
supports 'centos', '~> 6.5', '~> 7.0'
```

or 

``` ruby
supports 'centos', ['~> 6.5', '~> 7.0']
```

**Comment by lxndrp** [comment]
I guess what needs to be specified first is the exact semantics of the notation (whichever variant will be used in the end). That is, what does something like `supports 'foo', ['~> 1.5', '~> 1.8']` exactly mean:
 * Both versions independently, up to the semver constraints
 * Both versions together, within the semver constraints

Plus, what about edge cases like 'lower than x, higher than y':
 * Everything smaller or greater than
 * smaller or greater than independently, but not the excluded part

Unless this is clearly defined, the discussion on the notation should be postponed IMHO.

**Comment by Zenexer** [comment]
@lxndrp That sounds unnecessarily complex.  A simple whitelist/blacklist system should suffice.

Here's the current proposal, as I understand it:

> A whitelist is supported.  If a whitelist exists, all versions not covered by the whitelist are deemed unsupported.

As currently implemented, the whitelist can only contain a single specifier; we would be removing this limitation.

Now, we're adding to the proposal:

> A blacklist is supported.  The blacklist takes precedence over the whitelist.

This gives the following possible scenarios:

* **Neither a whitelist nor a blacklist is specified**: All versions are supported.
* **A whitelist is specified, but no blacklist**: Only the versions covered by the whitelist are supported.
* **A blacklist is specified, but no whitelist**: All versions are supported except those covered by the blacklist.
* **Both a whitelist and a blacklist are specified**: Only the versions covered by the whitelist and not by the blacklist are supported.

It would be possible to blacklist all versions this way.  However, it would be a waste of time for chef to test for such a case, because any attempt to test the cookbook on a system that the author intends to support will reveal the error.

**Comment by lxndrp** [comment]
Sounds reasonable to me. Don't get me wrong, I didn't intend to make it overcomplicated, but supporting semver style version selectors makes the implementation much harder.

So what we basically get is a white (or black) list of specific versions, i.e. `'1.7', '2.0'` which would be included (or excluded), correct?

**Comment by Zenexer** [comment]
Well, for the combination of white listing and blacklisting to be useful, selectors would still have to be supported.  In theory, implementation shouldn't be much harder.

**Comment by stevendanna** [comment]
We looked at this issue during a triage of some of the chef-server ticket.  It is relatively straightforward to support this on the API side (depending on the signature, we might already support it), but as y'all have correctly honed in on, the question that we need to answer first is what we actually want client-side.  I've left a comment on the original ticket

https://github.com/chef/chef/issues/2457

to also hopefully pull in some of the client maintainers back into this discussion.

**Comment by PrajaktaPurohit** [comment]
Closing this issue since the Chef Client side issue for this is closed.
