### ISSUE TITLE
Add flexibility to allow UI to render on a non-standard port (non 80 nor 443)

### ISSUE THREAD

**Issue by vinyar** [chef/chef-server#358]
probably via attribute. 

more info incoming from @solverdude

**Comment by mmzyk** [comment]
@vinyar What UI are we talking about? oc-id or Chef Manage?

**Comment by SolverDude** [comment]
We're speaking of Chef Manage specifically.

The original intent of this was to separate the traffic for opscode-manage completely from the ssl port.  We have nodes which are more highly secure that we wish to manage via Chef, and part of that was to only allow convergence traffic on ssl port.

This was also based on our initial bias that all the frontend servers be within a load balancer.  I had the epiphany that if we had one frontend OUT of the load balancer, and that one was the frontend with opscode-manage installed, we'd solve our needs elegantly.  Looks slightly obvious, but no one internal or external to us ever suggested this.

We're going to confirm all's well with that this week, and I'll advise if that renders this issue effectively moot.

**Comment by mmzyk** [comment]
@SolverDude Thanks. The reason I asked for clarification is that we have https://github.com/chef/chef-manage-issues for filing issues like this, since Chef Manage is not shipped as a default part of the Chef server, as an fyi.

If this does end up being an issue that you confirm, can you open the issue on that repo instead? In the meantime, I'll close this one for bookkeeping purposes. Opening on the right issue will ensure the right team sees it.

Thanks.
