### ISSUE TITLE
network connections on chef-server

### ISSUE THREAD

**Issue by sdarwin** [chef/chef-server#412]
Hello,
Checking network connections on a brand new chef server, version 12.1.0 , Ubuntu 14.04, without any clients or cookbooks:

netstat -anptu

There are well over 1000 chef-related network connections or listening ports.   To be more specific:

netstat -anptu | grep udp | grep beam | wc

udp        0      0 0.0.0.0:37201           0.0.0.0:\*                           14080/beam.smp
udp        0      0 0.0.0.0:38227           0.0.0.0:\*                           13626/beam

a total of 1050 

netstat -anptu | grep tcp | grep beam | wc

tcp        0      0 127.0.0.1:44001         127.0.0.1:5432          ESTABLISHED 5952/beam

a total of 67

Is this expected?  Is it a concern?   Might this be tuned to an order-of-magnitude smaller value?  :-)

**Comment by stevendanna** [comment]
@sdarwin What you are seeing does look expected (I can't account for every connection without seeing them all).  Here is an explanation of some of what you are seeing:

beam.smp is the erlang runtime.  We have 5 erlang services: erchef (the main API), bifrost (an internal authorization service), bookshelf (an s3 clone used for cookbook storage), and chef-mover (migration tooling for complicated upgrades), and rabbitmq. Below I've broken down some of what you should be seeing for TCP and UDP connections:

## TCP

### Erchef

Erchef makes TCP connections to postgresql (20 by default), rabbitmq (2 connections I believe), and 1 connection to epmd (part of erlang).  It also listens on port 8000 (where it serves the API) and a high numbered port (this port is erlang's internode communication features).  Thus erchef alone will produce 25 of those TCP connections you found.  During operation, you may see additional connections when erchef talks to bifrost and solr.

### Bifrost

Similarly, bifrost has a pool of 20 connections to postgresql. It connects to epmd. It listens on 2 ports (one for the service, one for erlang distributed stuff).  Making for 23 TCP connections.

### chef-mover

5 connections to postgresql by default, listens on 1 port, connects to epmd.  7 TCP connections total.

### bookshelf

2 listening ports, 1 connection to epmd. 3 TCP connections/listening ports total.

### rabbitmq

Listens on 2 ports.  1 connection to epmd.  And will have 2 established connections per client.  The number of clients is at least 2, but will go up with the number of CPUs you have.  Should be #CPUs + 1.  Thus, this is at least 7 TCP connections/listening ports.

That accounts for 65 (25+23+7+3+7) of those TCP connections.  The number will be higher as you make requests that require various HTTP connections and such.

## UDP

All of the UDP lines are coming from the service instrumentation we have.  Our services are emit statistics over UDP in the statsd format.  By default we create 350 "udp sender" workers.  Erchef, bifrost, and chef-mover all use this same library.  350*3 = 1050.

## Configuration

You can configure the number of postgresql connections will be added to the connection pool for each app with:

```
opscode_erchef['db_pool_size']
oc_bifrost['db_pool_size']
opscode_chef_mover['db_pool_size']
```

Unfortunately, it looks like while UDP pool size is configurable, it is linked to the postgresql max connections configurable.  Really, that should be its own configurable so that you can lower the number of UDP senders without also lowering the number of postgresql max connections.  I'll open a bug about that shortly.

**Comment by stevendanna** [comment]
I'm going to close this issue out.  I hope my explanation was helpful at the time.  The socket pool size is now configurable (as of 12.9.0) https://github.com/chef/chef-server/commit/6c435bd77d8372ef322e12070c72e78c78aa5329 separately from the max_connections configurable.

**Comment by sdarwin** [comment]
Thanks Steve!
