### ISSUE TITLE
postgres shared_buffers calculation is broken because values have different units

### ISSUE THREAD

**Issue by jeremiahsnapp** [chef/chef-server#44]
A system with 64GB of memory couldn't just install CS12 and have it work because the `postgres['shared_buffers']` value was being set too high. This kept postgresql from starting because it was trying to `shmget` more space than `shmmax` allowed.

The problem is that everything in the calculation code linked below uses values that have different units. Some are in kB and some are in bytes.

1. the ohai value in `node['memory']['total'].to_i` is in kB
2. shmmax value is bytes
3. shared_bytes is assumed to be in kB

My recommendation is that every value should be converted to bytes and then proceed with calculations.

https://github.com/opscode/opscode-omnibus/blob/12.0.0/files/private-chef-cookbooks/private-chef/attributes/default.rb#L377-L385

**Comment by acqant** [comment]
+1 to fix this

AND to get some semblance of how many different cookbooks are used to install a chef-server and what method is used to tune them.

https://github.com/chef-cookbooks/chef-server  says to drop configs into /etc/opscode/chef-server but it seems that if postgres doesn't start clean the reconfigure fails.

**Comment by mmzyk** [comment]
@acqant I'm not sure what your question is, exactly, but I'll see if I can clear up your confusion. The chef-server cookbook you linked to is a way to install a chef-server, but it isn't required. You can always just install the omnibus package and then run reconfigure and never use the chef-server cookbook you linked, for instance.

Now, as for why reconfigure fails when postgres fails to start, reconfigure is using the chef-server's embedded chef-client to apply configuration to and restart the chef-server. This includes making sure all the needed services are up and running, of which postgres is one, so if it fails it makes sense reconfigure will also fail.

Since reconfigure is just doing a chef run under the hood, it's using a set of chef cookbooks that are included with the chef server for configuring the chef server. @jeremiahsnapp Linked to one of those cookbooks. The entire set of cookbooks (excluding some HA ones) can be found here: https://github.com/chef/chef-server/tree/master/omnibus/files/private-chef-cookbooks/private-chef

That contains all the cookbooks and configuration for a chef-server. /etc/opscode/chef-server.rb comes into play as a place you can define various config options. reconfigure will then look there and those options will get applied as attributes in the chef run, overriding the default options set in the cookbooks I just linked. /set/opscode/chef-server.rb is not overwritten on upgrade, so those options will continue to apply, even if the default options in the embedded cookbooks change. 

Does that all makes sense? Hopefully that clears up how it all works.

**Comment by mmzyk** [comment]
@jeremiahsnapp Any one who encounters this until this fix is put in should be able to work around it by setting the shmall and shmmax values themselves, correct? 

https://docs.chef.io/config_rb_server_optional_settings.html#postgresql

**Comment by thommay** [comment]
@mmzyk @acqant I think we cleared this up on IRC. I'm just testing a fix to the cookbook in omnibus to deal with this.
