### ISSUE TITLE
erchef / chef manage - status=412; ">>,"Precondition Failed" causes chef server to become unresponsive

### ISSUE THREAD

**Issue by craigmonson** [chef/chef-server#526]
* chef-server-core-12.0.7-1.el6.x86_64.rpm
* opscode-manage-1.11.4-1.el5.x86_64.rpm

In chef manage, when selecting an individual node, when the runlist is being queried (the spinner in the runlist section is displayed), if there is a missing cookbook version in the dependency tree, the chef server becomes unresponsive.  tail -f /var/log/opscode/opscode-erchef/erchef.log continuously logs: 

> 2015-09-11 14:09:49.274 [error] {<<"method=POST; path=/organizations/.../environments/int/cookbook_versions; status=412; ">>,"Precondition Failed"}
> 2015-09-11 14:09:49.720 [error] {<<"method=POST; path=/organizations/.../environments/int/cookbook_versions; status=412; ">>,"Precondition Failed"}

**Comment by smith** [comment]
This was fixed in Manage 1.20.1: https://www.chef.io/blog/2015/08/13/chef-management-console-1-20-1-release/. Please try using that release (or the latest stable, 1.21.1) and reopen this if you still experience this problem.

For future reference you can open issues for Chef Manage on the [chef-manage-issues](https://github.com/chef/chef-manage-issues/issues) repository.

**Comment by smith** [comment]
I believe this was originally reported in chef/chef-manage-issues#69.

**Comment by craigmonson** [comment]
Awesome, thanks for the quick reply.

**Comment by rjaros87** [comment]
The same problem as described in first post by @craigmonson 
`2015-09-22 10:46:04.400 [error] {<<"method=POST; path=/organizations/.../environments/_default/cookbook_versions; status=412; ">>,"Precondition Failed"}`

but I use Chef Server 12.2.0 and Chef Manage 1.21.0

reopen?

**Comment by kishorerc** [comment]
Looks like this issue is not resolved yet. Please see the below error.  During this time the cpu is 100%
Error:
{<<"method=PUT; path=/organizations/chef-org/nodes/nodename; status=404; ">>,"Not Found"}
2017-02-15 11:57:57 =ERROR REPORT====
{<<"method=POST; path=/organizations/chef-org/environments/_default/cookbook_versions; status=412; ">>,"Precondition Failed"}
2017-02-15 13:25:44 =ERROR REPORT====
{<<"method=POST; path=/organizations/chef-org/environments/_default/cookbook_versions; status=412; ">>,"Precondition Failed"}

Chef Server details:
chef-server-core-12.7.0-1.el6.x86_64
chef-manage-2.4.0-1.el6.x86_64
