### ISSUE TITLE
oc_id: email configuration

### ISSUE THREAD

**Issue by dissonanz** [chef/chef-server#547]
I'm setting up an open source Chef 12 server with supermarket, and the password reset service from oc_id fails because the origin host is not set in the production.yml file. Additionally, the from: address is also not overridden.

I've managed to workaround the problem by creating a settings.local.yml file in `/opt/opscode/embedded/service/oc_id/config` containing the following lines:

```
email_from_address: 'Chef Notifications <chef@notchef.io>'
origin: chef.notchef.io
```

But it would be far better to have these lines included in `/var/opt/opscode/oc_id/config/production.yml`

**Comment by pmoosh** [comment]
+1

**Comment by smith** [comment]
The correct way to fix this will be to add these options to be configurable in [chef-server.rb](https://docs.chef.io/config_rb_server_optional_settings.html#oc-id). The options should be added here: https://github.com/chef/chef-server/blob/cd2ec8d79dd72176b73f5e50ed48edd212b3cb7b/omnibus/files/private-chef-cookbooks/private-chef/attributes/default.rb#L539-L575 and here https://github.com/chef/chef-server/blob/cd2ec8d79dd72176b73f5e50ed48edd212b3cb7b/omnibus/files/private-chef-cookbooks/private-chef/recipes/oc_id.rb#L27-L38

Then, in your chef-server.rb you could do:

```
oc_id['email_from_address'] 'Chef Notifications <chef@notchef.io>'
oc_id['origin'] 'chef.notchef.io'
```

The `oc_id` options from that file get written out to production.yml when you `chef-server-ctl reconfigure`: https://github.com/chef/chef-server/blob/cd2ec8d79dd72176b73f5e50ed48edd212b3cb7b/omnibus/files/private-chef-cookbooks/private-chef/recipes/oc_id.rb#L78-L84

The settings.local.yml should override what's in the production.yml (we're using https://github.com/railsconfig/config), so that's probably the best workaround for now, but it might also be a good idea to place the file outside of /opt and symlink it to avoid the possibility of it being wiped out on an upgrade.
