### ISSUE TITLE
Unable to set topology from dna.json file

### ISSUE THREAD

**Issue by poliva83** [chef/chef-server#583]
I've noticed that you override some values in your dna.json file but not all. Topology is one value you can only override in /etc/opscode/chef-server.rb.

```
root@chef-server-tmp-1445653166:~# cat /opt/opscode/embedded/cookbooks/dna.json
{
    "run_list": [
        "recipe[private-chef::default]"
    ],
    "private_chef": {
        "enabled-plugins": [
            "chef-ha-opennebula"
        ],
        "topology": "ha",
        "servers": {
            "chef-server-tmp-1445653166": {
                "ipaddress": "10.236.231.53",
                "role": "backend",
                "bootstrap": false
            }
        }
    }
}
```

When triggering reconfigure to following attributes are different, and the topology ends up being 'standalone'.

node['private_chef']['topology'] ... results in 'ha'
PrivateChef["topology"] ... results in 'standalone'

**Comment by stevendanna** [comment]
@poliva83 Thanks for taking the time to file this issue, apologies no one has responded to it since you filed it.  

I think that we want to keep `dna.json` as an internal implementation detail and not make guarantees about what is or is not settable from that file.  Do you have a particular need to set the topology in that file verse the main `chef-server.rb` configuration file?

**Comment by poliva83** [comment]
@stevendanna This issue is over year old now. I was experimenting using `/opt/opscode/embedded/cookbooks/dna.json` instead maintaining `/etc/opscode/chef-server.rb`.  The json format seemed a little easier to maintain in my cookbook's template then the ruby file. Anyway I since abandoned that idea so feel free to close this.

**Comment by stevendanna** [comment]
@poliva83 Thanks for following up.  Again, apologies this wasn't addressed at the time.
