### ISSUE TITLE
Chef 12 opscode-reporting bootstrap is failing behind a proxy

### ISSUE THREAD

**Issue by nkaravias** [chef/chef-server#590]
On a fresh Chef 12 server (12.2.0-1 on OEL 6.5 x64) I've installed the opscode-reporting package and I'm trying to configure it. The host that's running the Chef server only has access to the net via a web proxy and $no_proxy is properly set to 127.0.0.1,localhost on the environment and on /opt/opscode-reporting/embedded/cookbooks/solo.rb.

Running opscode-reporting-ctl reconfigure seems to break because it cant connect to chef zero. For the duration of the converge (for opscode-reporting-ctl reconfigure) I was able to see that chef-zero is indeed up and listening on localhost:8889. However the client is not able to connect to it (my guess is because it's ignoring $no_proxy and my proxy server is blocking it). Any ideas?

Here's a snippet of the output of opscode-reporting-ctl reconfigure

- configure service runit_service[opscode-reporting]
Recipe: opscode-reporting::oc-reporting-pedant
  * template[/etc/opscode-reporting/pedant_config.rb] action create (up to date)
Recipe: opscode-reporting::default
  * file[/etc/opscode-reporting/opscode-reporting-running.json] action create (up to date)
[2015-10-29T13:25:53-07:00] ERROR: Timeout connecting to http://127.0.0.1:8889/nodes/den00qcw.local.com, retry 1/5
http://127.0.0.1:8889/nodes/den00qcw.local.com, retry 2/5
http://127.0.0.1:8889/nodes/den00qcw.local.com, retry 3/5
http://127.0.0.1:8889/nodes/den00qcw.local.com, retry 4/5
http://127.0.0.1:8889/nodes/den00qcw.local.com, retry 5/5
^Running handlers:
[2015-10-29T14:22:01-07:00] ERROR: Running exception handlers
Running handlers complete

[2015-10-29T14:22:01-07:00] ERROR: Exception handlers complete
[2015-10-29T14:22:01-07:00] FATAL: Stacktrace dumped to /opt/opscode-reporting/embedded/cookbooks/cache/chef-stacktrace.out
Chef Client failed. 5 resources updated in 2677.812041135 seconds
[2015-10-29T14:22:01-07:00] ERROR: Timeout connecting to http://127.0.0.1:8889/nodes/den00qcw.local.com, giving up

**Comment by stevendanna** [comment]
@metadave Looks like we might want something like: https://github.com/chef/chef-server/commit/b6e804108a041e9dd650ef2fd8f756e433f0a521 in the config that opscode-reporting-ctl is using.

**Comment by metadave** [comment]
ok, we'll take a look. logged as IN-89 internally

**Comment by jeremiahsnapp** [comment]
I don't think this has anything to do with proxies. I have two other users reporting the same issue and one for sure isn't using proxies.

The user I worked with was seeing this as a result of their Linux system being configured for LDAP or Active Directory authentication. Ohai's `Passwd` plugin gathers all of the LDAP/AD users and groups which results in a large enough node data to cause problems when ffi-yajl parses the JSON.

The embedded chef 11.12.2 uses chef-zero 2.1.2 for `--local-mode`. The chef-zero instance parses JSON using the embedded ffi-yajl 1.4.0 which has performance issues that weren't fixed until ffi-yajl 2.1.0.

Large node data is causing chef-zero to spend a significant time parsing JSON which means it can't send its HTTP response fast enough which results in the timeouts seen.

I've been able to reproduce this on a clean install of opscode-reporting 1.5.1 by simply creating node data larger than 1.5 megabytes using the following script, which creates a large number of linux users and groups, and then running the reconfigure command.

```
for i in {2000..8999}; do echo "tester-$i:x:$i:$i:::" >> /etc/passwd; echo "tester-$i:x:$i:" >> /etc/group; done
opscode-reporting-ctl reconfigure
```

You can run the following command as a simple test to see if your system has large node data. It uses ohai to collect the node data and then counts the number of bytes in the output.

```
ohai | wc --bytes
```

A quick workaround that works for me is to downgrade chef-zero to version 2.2 which uses the standard json library instead of ffi-yajl. Running the following commands exactly as given below will properly downgrade chef-zero.

```
/opt/opscode-reporting/embedded/bin/gem install chef-zero -v 2.2 --no-ri --no-rdoc
/opt/opscode-reporting/embedded/bin/gem uninstall chef-zero -v 2.2.1
```

A long term solution should be configuring opscode-reporting to use the latest versions of chef which in turn will use fixed versions of chef-zero and ffi-yajl.

**Comment by nkaravias** [comment]
Thanks, this fixed it. Is there a plan to include the newer version of chef-zero on a future version of the chef server?

**Comment by datascope** [comment]
I know this is closed - but if there are others with this ... What we faced is that in a large organization under Active Directory, the number of credentials information is ginormous so in 
```
/opt/opscode-reporting/embedded/cookbooks/solo.rb
```
add
```Ohai::Config[:disabled_plugins] = [ :Passwd ]```

then re-ren reconfigure
