### ISSUE TITLE
chef-server-ctl upgrade broken in 12.4.0

### ISSUE THREAD

**Issue by coderanger** [chef/chef-server#724]
The upgrade process from 11 to 12 uses `knife-ec-backup` internally, which requires [`chef/chef_fs/file_system_acl_entry`](https://github.com/chef/knife-ec-backup/blob/master/lib/chef/knife/ec_restore.rb#L29) but this file was [removed between 12.6.0 and current master](https://github.com/chef/chef/commit/6d9c8b03466632b3cd11042a2b99a08ae5047309). The fix probably needs to go in knife-ec-backup but tracking this here because it will require a new Chef Server build too.

**Comment by coderanger** [comment]
Ping @danielsdeleo @jkeiser

**Comment by coderanger** [comment]
Alternatively maybe we should revert the path change in Chef until Chef 13 and then rebuild Chef Server with that.

**Comment by jkeiser** [comment]
@coderanger we should just add whatever files really need to be there to https://github.com/chef/chef/tree/master/lib-backcompat/chef/chef_fs/file_system

**Comment by coderanger** [comment]
Works for me :)

**Comment by stevendanna** [comment]
:+1: On getting backcompat paths in Chef.  `knife-ec-backup` tries to be compatible with a wide-range of chef versions so that users can install it into the ruby gemsets that shipped on older chef-servers that didn't include it out of the box.  I think we are getting to the point, however, where this isn't a reasonable goal so I might still update the knife-ec-backup `require` statements to match latest and the provide instructions on how to install knife-ec-backup into a local chefdk.

**Comment by stevendanna** [comment]
@dmccown @tylercloke We will want to see why upgrade testing didn't catch this.  I've posted some notes in Slack related to what I think happened but it would be great if you could double check.

**Comment by btm** [comment]
Apparently, Chef Server builds pull from Chef Client master and Chef Server 12.4.0 picked up the change that was fixed in chef#4499.

https://github.com/chef/chef-server/blob/master/omnibus/config/projects/chef-server.rb#L95

**Comment by mmzyk** [comment]
This fix when out in the 12.4.1 release: https://www.chef.io/blog/2016/02/04/chef-server-12-4-1-release/
