### ISSUE TITLE
Hosted Chef Should Support User Manipulation Through the API

### ISSUE THREAD

**Issue by sean-horn** [chef/chef-server#77]
As a Hosted Chef customer, I would like to be able to Add/Remove/Invite/Disassociate users from the command line using an already authenticated Admin-member user in an org, rather than through the Manage interface.

Manage slows me down for this usage, and I would like to speed up.

**Comment by marcparadise** [comment]
The API actually fully supports this (it's how manage does it).  I believe it's just a matter of adding support to knife.

**Comment by jkess** [comment]
@marcparadise - Could you provide some examples of how to handle this via the REST API on Hosted Chef? I don't believe all methods are exposed to Hosted Chef users, especially the /users endpoint.

**Comment by cheaprbytheduzn** [comment]
+1 to jkess' request.  In particular, how might one accept an invitation to an organization from the command line?

**Comment by marcparadise** [comment]
@jkess The price of an incompletely documented API :) I'll get some examples here over the next day.

 @cheaprbytheduzn a quick answer to  your question - authenticate as the invited user, and  `PUT /users/$name/association_requests/$INVITE_ID` with content `{ "response" : "accept" }`.  Or if you want to reject the invite, use `"response":"reject"`.

For non-Hosted installations of CS12+, authenticating as the global admin user also gives you the ability to directly associate users, using `POST /organizations/$NAME/users` with body content { "username" : "$USER"}`.  This will not work in Hosted.

**Comment by marcparadise** [comment]
Here's an example using knife raw of how to list and delete association requests: 

https://github.com/chef/chef-docs/pull/382/files

This can be modified for a user to accept an invite if you change the .chef/knife.rb with: 

`chef_server_url "https://api.opscode.piab"` 

This will have all requests go to the root instead of the organization-specific path, so that you can then: 

`knife raw -m PUT "/users/$USER/association_requests/$ID" { "response" => "accept" }`

(Again, the request will have to be authenticated as $USER.)

**Comment by marcparadise** [comment]
Any objections to closing this?

**Comment by jkess** [comment]
Feel free to close it.
