### ISSUE TITLE
org-user-add -a flag does not give billing-admin rights.

### ISSUE THREAD

**Issue by FearTheBadger** [chef/chef-server#97]
I ran in to a case where I created a new organization but didn't associate a user at creating. I then after the fact added a user with org-user-add setting the -a flag to make that user an admin. org-user-add added the user and made them a normal admin, but did not give them billing-admin rights. I could find no way to give any user the rights to view/modify billing-admins without deleting the org and re-creating. I'm not sure if this is by design or if it is a bug. Either way a method for adding a user to billing-admins when there is no one currently holding the role, would be much appreciated.

**Comment by stevendanna** [comment]
@FearTheBadger I've opened chef/knife-opc#26 to track a similar issue in the upstream project that would need to change in order to get this feature.

Out of curiosity, what are you using the billing-admin group for?  That group is mostly an artifact of chef-server's Hosted Chef origins where it is used to control who can view and change billing information.

**Comment by FearTheBadger** [comment]
Oh I've never used, or have any use for it at this time.  I just noticed it when I was setting up v12 Chef for the first time.  I was coming from v11 and was exploring the new things coming with the upgrade.
