### ISSUE TITLE
Allow Hosted Chef Server to Refer to AWS S3 US-STANDARD Endpoint at s3.amazonaws.com

### ISSUE THREAD

**Issue by sean-horn** [chef/chef-server#99]
The crux of the matter is the point where the chef server tries to commit the sandbox and cannot find the expected file. The server must have a way to wait until the expected files have shown up, or provide a good error message about what happened.

http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region

ZenDesk 3030

**Comment by stevendanna** [comment]
# Background

## Cookbook Storage Location

All cookbook data on Hosted Chef is stored on Amazon's S3 service.  We store the data in a bucket in the US Standard S3 region.  API requests for US Standard can be made via two endpoints:

- s3.amazonaws.com
- s3-external-1.amazonaws.com

s3-external-1 resolves to S3's east coast locations.  s3.amazonaws.com resolves to either their west coast or east coast location, based on location.  Even when s3.amazonaws.com resolves to a west coast location, you are still hitting the US Standard region as far as buckets, access controls, and consistency guarantees are concerned.

All upload and download links we generate use s3-external-1 API endpoint.

## Cookbook Upload Process

When uploading a cookbook, the following happens:

1) The user sends the Chef Server a list of checksums that correspond to the files they have on disk for that cookbook. (POST /sandboxes)

2) We send back a "sandbox" object that has a list of the checksums that the user has to upload and s3 links that the user should use to upload the files. (response to the previous put)

3) The user uploads the files to the appropriate s3 locations 

4) The user tells the Chef Server that it is done uploading (PUT /sandboxes/GUID)

5) The Chef Server validates that all of the files the user was supposed to upload are present in S3. If so, it sends a response indicated that the cookbook is "uploaded/committed"

6) The user then uploads the metadata for the cookbook.

# Why we point at s3-external-1

In early January of 2013 support found that nearly all uploads to Hosted Chef were failing.  The logs from the failure indicated that the check in step (5) above was failing, even in cases when the user uploaded the files to S3 properly.  At the time, we were using the s3.amazonaws.com and the checks were failing because many users were uploading to US Standard's west coast datacenter while Hosted Chef was being routed to the East Coast data centers.  Since US Standard (unlike other regions) does NOT provide read-after-right guarantees, the Hosted Chef Servers would receive 404s on files that were not yet consistently available on both the east and west coast.

We resolved the issue my ensuring all users uploaded to the east coast locations by changing to the s3-external-1 endpoint.  

We also considered migrating the data to a different region that provides read-after-write consistency.  However, at the time of that analysis, even listing the entire content of the cookbook store took hours, leading us to believe that any migration would likely be extremely time consuming.

**Comment by manderson26** [comment]
We don't intend to tackle this at this time. This should be revisited at later date, but the complexity of fixing this high, and would require a lot of testing to verify we don't reintroduce the issues mentioned above.
